name: Prettier

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Install dependencies
              run: npm ci

            - name: Prettify code
              run: npm run prettier:fix

            - name: Commit and push changes
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'actions@github.com'
                  git commit -am 'Prettified Code!' || :
                  git push
